# What is Pandas?

Pandas is an open-source Python library for data manipulation and analysis. It gives you 
powerful, fast, flexible, and expressive data structures designed to work with structured data.

It is built on top of NumPy, and its name comes from “Panel Data” (econometrics term for multidimensional data).

# Why Pandas? What problem does it solve?

### Before Pandas:

People used raw Python lists, dictionaries, or NumPy arrays.

These structures lacked labels, indexing, grouping, join/merge, handling missing data, etc.

Real-world datasets (CSV, JSON, Excel, SQL) are structured in rows and columns — not arrays.

So Pandas was designed to work like:

📊 Excel + 🧮 NumPy + 🗂️ SQL + 🧰 ETL tools — inside Python

# ⚙️ Where is Pandas used?

| Field              | How Pandas Helps                                        |
| ------------------ | ------------------------------------------------------- |
| Data Science       | Load, clean, explore, transform, and model data         |
| Machine Learning   | Prepare features, preprocess, manipulate large datasets |
| Finance            | Time series, stock prices, trade records                |
| Web/Data Analytics | ETL pipelines, server logs, product usage stats         |
| Healthcare         | Patient records, diagnostics, hospital statistics       |

# 🧱 What does Pandas offer at its core?

| Core Object          | Description                                   |
| -------------------- | --------------------------------------------- |
| `Series`             | 1D labeled array — like a column              |
| `DataFrame`          | 2D table — like a sheet of Excel or SQL table |
| `Panel` (deprecated) | 3D data container (replaced by MultiIndex)    |

# 🎁 And tons of utilities:

- Reading/Writing (CSV, JSON, Excel, SQL, Parquet)

- Powerful slicing/indexing/merging

- GroupBy, pivoting, reshaping

- Time series and date handling

- Missing data handling

- Statistical functions and window operations

- Built-in plotting (with matplotlib backend)

Think of Pandas like a spreadsheet that you can program, automate, and scale — with the power of Python and NumPy underneath.

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset_url="https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

In [4]:
df=pd.read_csv(dataset_url)

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [8]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [9]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [10]:
df[['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [11]:
df.shape

(891, 12)

In [12]:
dir(df)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'T',
 'Ticket',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [13]:
data=[1,2,3,4,5]
s1=pd.Series(data)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
s2=pd.Series(data=data,index=['a','b','c','d','e'],name='Numbers')
s2

a    1
b    2
c    3
d    4
e    5
Name: Numbers, dtype: int64

In [15]:
data={"a":1,"b":2,"c":3}
s3=pd.Series(data=data)
s3

a    1
b    2
c    3
dtype: int64

In [16]:
data=np.array([10,20,30])
s4=pd.Series(data=data,index=["A","B","C"])
s4

A    10
B    20
C    30
dtype: int64

In [17]:
s5=pd.Series(data=[10,20,30,40,50],index=["A","B","C","E","F"],name="Score")
s5

A    10
B    20
C    30
E    40
F    50
Name: Score, dtype: int64

In [18]:
print(s5)
print(s5.index)
print(s5.values)
print(s5.dtype)
print(s5.name)
print(s5.shape)
type(s5.shape)

A    10
B    20
C    30
E    40
F    50
Name: Score, dtype: int64
Index(['A', 'B', 'C', 'E', 'F'], dtype='object')
[10 20 30 40 50]
int64
Score
(5,)

tuple

#### Series Indexing & Access

In [19]:
print(s5.values[0])
print(s5.values[3])

10
40

In [20]:
print(s5.iloc[0])
print(s5.iloc[3])

10
40

In [21]:
print(s5.iloc[0:3])

A    10
B    20
C    30
Name: Score, dtype: int64

In [22]:
print(s5[0])

10

C:\Users\zahee\AppData\Local\Temp\ipykernel_14868\3134925317.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s5[0])

In [23]:
print(s5['A'])

10

In [24]:
print(s5['B'])

20

In [25]:
print(s5[['A','B']])

A    10
B    20
Name: Score, dtype: int64

In [26]:
print(s5.loc['A'])

10

In [27]:
print(s5.loc[["A","B"]])

A    10
B    20
Name: Score, dtype: int64

In [28]:
s3=pd.Series([10,20,30,40,50])
s3.iloc[[1,2]]

1    20
2    30
dtype: int64

In [29]:
s3.iloc[1:3]

1    20
2    30
dtype: int64

In [30]:
s3.loc[[1,2]]

1    20
2    30
dtype: int64

# 2. What is a DataFrame?

A DataFrame is a 2D labeled data structure with columns of potentially different types, just like a spreadsheet or SQL table.

Think of it like:

- A dict of Series

- Or a table with rows and columns

It is the core structure of pandas used for:

- Reading, cleaning, transforming, analyzing, and exporting data


### Why DataFrame?

Real-world data is usually tabular (e.g., CSV, Excel, SQL)

Rows = records

Columns = features

It supports label-based indexing, automatic alignment, missing data handling, grouping, aggregation, and more


| Concept     | Real-Life Analogy             |
| ----------- | ----------------------------- |
| `DataFrame` | Excel sheet or database table |
| `Series`    | One column of that sheet      |
| Index       | Row number or ID              |
| Columns     | Named headers                 |

In [31]:
data={
    "name":["Zaheer","Sanju","Shashank","Nandini","Nisarga"],
    "usn":[30,46,44,26,28],
    "city":["Gulbarga","Hubli","Mysore","Bengaluru","Hyderabad"]
}

In [32]:
df=pd.DataFrame(data=data)

In [33]:
print(df)

       name  usn       city
0    Zaheer   30   Gulbarga
1     Sanju   46      Hubli
2  Shashank   44     Mysore
3   Nandini   26  Bengaluru
4   Nisarga   28  Hyderabad

In [34]:
df

       name  usn       city
0    Zaheer   30   Gulbarga
1     Sanju   46      Hubli
2  Shashank   44     Mysore
3   Nandini   26  Bengaluru
4   Nisarga   28  Hyderabad

In [35]:
data=[
    {"name":"zaheer","usn":30,"city":"Gulbarga"},
    {"name":"sanju","usn":46,"city":"Hubli"},
    {"name":"Shashank","usn":44,"city":"Aurad"},
    {"name":"Nandini","usn":26,"city":"Mysore"},
    {"name":"Nisarga","usn":28,"city":"Hyderabad"}
]
df=pd.DataFrame(data)
df

       name  usn       city
0    zaheer   30   Gulbarga
1     sanju   46      Hubli
2  Shashank   44      Aurad
3   Nandini   26     Mysore
4   Nisarga   28  Hyderabad

In [36]:
array=np.array([[1,2],[3,4],[5,6]])
df=pd.DataFrame(array,columns=["A","B"])
df

   A  B
0  1  2
1  3  4
2  5  6

In [37]:
data={
    "name":["Zaheer","Sanju","Shashank","Nandini","Nisarga"],
    "usn":[30,46,44,26,28],
    "city":["Gulbarga","Hubli","Mysore","Bengaluru","Hyderabad"]
}
df=pd.DataFrame(data)
df

       name  usn       city
0    Zaheer   30   Gulbarga
1     Sanju   46      Hubli
2  Shashank   44     Mysore
3   Nandini   26  Bengaluru
4   Nisarga   28  Hyderabad

In [38]:
print(df['name'])
print("=============")
print(df[['name','usn']])
print("=============")
print(df.iloc[0])
print("=============")
print(df.loc[1])

0      Zaheer
1       Sanju
2    Shashank
3     Nandini
4     Nisarga
Name: name, dtype: object
=============
       name  usn
0    Zaheer   30
1     Sanju   46
2  Shashank   44
3   Nandini   26
4   Nisarga   28
=============
name      Zaheer
usn           30
city    Gulbarga
Name: 0, dtype: object
=============
name    Sanju
usn        46
city    Hubli
Name: 1, dtype: object

# Working with real dataset

In [39]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [40]:
df=pd.read_csv(titanic_dataset_github_url)

In [41]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [42]:
print(df.head())
print(df.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S

In [43]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [44]:
display(df.head(3))
display(df.head(1))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [45]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [46]:
df[['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [47]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [48]:
df.loc[0]['Name']

'Braund, Mr. Owen Harris'

In [49]:
df.loc[0,'Name']

'Braund, Mr. Owen Harris'

In [50]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [51]:
df.loc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [52]:
df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [53]:
df.iloc[0:5,3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

# Loading from local csv file

In [54]:
df=pd.read_csv('titanic.csv')
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

# 5. Conditional Selection (Boolean Indexing)

In [55]:
df['Age']>70

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [56]:
df[df['Age']>70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [57]:
old_passengers=df[df['Age']>70]
old_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [58]:
old_passengers.shape

(5, 12)

In [59]:
old_passengers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 96 to 851
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  5 non-null      int64
 1   Survived     5 non-null      int64
 2   Pclass       5 non-null      int64
 3   Name         5 non-null      object
 4   Sex          5 non-null      object
 5   Age          5 non-null      float64
 6   SibSp        5 non-null      int64
 7   Parch        5 non-null      int64
 8   Ticket       5 non-null      object
 9   Fare         5 non-null      float64
 10  Cabin        2 non-null      object
 11  Embarked     5 non-null      object
dtypes: float64(2), int64(5), object(5)
memory usage: 520.0+ bytes

In [60]:
old_passengers.describe()

       PassengerId  Survived    Pclass        Age  SibSp  Parch       Fare
count     5.000000  5.000000  5.000000   5.000000    5.0    5.0   5.000000
mean    438.200000  0.200000  1.800000  73.300000    0.0    0.0  25.936680
std     328.292096  0.447214  1.095445   3.993745    0.0    0.0  18.086844
min      97.000000  0.000000  1.000000  70.500000    0.0    0.0   7.750000
25%     117.000000  0.000000  1.000000  71.000000    0.0    0.0   7.775000
50%     494.000000  0.000000  1.000000  71.000000    0.0    0.0  30.000000
75%     631.000000  0.000000  3.000000  74.000000    0.0    0.0  34.654200
max     852.000000  1.000000  3.000000  80.000000    0.0    0.0  49.504200

In [61]:
old_passengers['PassengerId'].describe()

count      5.000000
mean     438.200000
std      328.292096
min       97.000000
25%      117.000000
50%      494.000000
75%      631.000000
max      852.000000
Name: PassengerId, dtype: float64

In [62]:
df[(df['Sex']=='female') & (df['Survived']==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [63]:
female=df[(df['Sex']=='female') & (df['Survived']==1)][['Name','Age']]
female.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [64]:
df.loc[((df['Sex']=='female') & (df['Survived']==1)),['Name','Age']]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

# 6. Slicing Rows and Columns Together

In [65]:
df.loc[:4,["Name","Age"]]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [66]:
df.iloc[0:3,0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [67]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [68]:
df.iloc[0:3,[3,1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

# Set Index (Optional)

In [69]:
df_by_passenger_id=df.set_index('PassengerId')

In [70]:
df_by_passenger_id.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [71]:
df_by_passenger_id.iloc[0]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [72]:
df_by_passenger_id.iloc[1]

Survived                                                    1
Pclass                                                      1
Name        Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                    female
Age                                                      38.0
SibSp                                                       1
Parch                                                       0
Ticket                                               PC 17599
Fare                                                  71.2833
Cabin                                                     C85
Embarked                                                    C
Name: 2, dtype: object

In [73]:
df_by_passenger_id=df_by_passenger_id.reset_index()

In [74]:
df_by_passenger_id.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [75]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [76]:
df=pd.read_csv(titanic_dataset_github_url)

In [77]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [78]:
df_by_passenger_id=df.set_index('PassengerId')

In [79]:
df_by_passenger_id

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [80]:
df_by_name=df.set_index('Name')

In [81]:
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [82]:
print(df_by_name.loc['Allen, Miss. Elisabeth Walton'])

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

# Are Subsets Views or Copies in Pandas?

In pandas, whether you get a view (linked to original DataFrame) or a copy (independent) 
depends on how you slice or filter — and it’s not always obvious.

- .iloc always returns a copy (safe, independent subset.)
- .loc may return a view (especially if indexing on labels)
    ```bash
    subset = df.loc[df['Sex'] == 'male']
    This is like the earlier filtering — might be a view.

    so..
    subset = df.loc[df['Sex'] == 'male'].copy()

    ```

| Situation                          | View or Copy? | Should you use `.copy()`? |
| ---------------------------------- | ------------- | ------------------------- |
| `.iloc[]` slicing                  | Mostly Copy   | Optional                  |
| `.loc[]` slicing                   | May be View   | Recommended               |
| Filtering with condition `df[...]` | May be View   | Recommended               |
| You plan to modify the subset      | Use `.copy()` | YES                       |

In [83]:
subest=df[df['Sex']=='male']
subest['Age']=subest['Age']+1

C:\Users\zahee\AppData\Local\Temp\ipykernel_14868\3701855563.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subest['Age']=subest['Age']+1

In [84]:
subest=df[df['Sex']=='male'].copy()
subest['Age']+=1

In [85]:
subest.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S

# Set Index vs Re - index

| Feature       | `set_index()`                               | `reindex()`                                          |
| ------------- | ------------------------------------------- | ---------------------------------------------------- |
| What it does  | **Moves a column** to become the index      | **Changes the row/column labels** of a DataFrame     |
| Main Use Case | Change the row labels using existing column | Match to new labels, add/remove/reorder rows/columns |
| Affects index | Yes – creates a **new index from a column** | Yes – but just **remaps or aligns to new index**     |
| Adds NaNs?    | No – only restructures                      | Yes – can insert NaNs for new labels                 |

# 1. set_index() — Use a column as the new index

In [86]:
df_by_name=df.set_index('Name')
print(df_by_name.loc["Allen, Miss. Elisabeth Walton"])

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [87]:
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [88]:
df_by_name=df_by_name.reset_index()

In [89]:
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

# 2. reindex() — Conform to a new index/column structure

In [90]:
sales_jan=pd.DataFrame({
    'Sales':[250,400,300],
},index=["Store_A","Store_B","Store_C"]
)

In [91]:
sales_feb=pd.DataFrame({
    'Sales':[260,310]
},index=['Store_A','Store_C'])

In [92]:
common_index=sales_jan.index
print(common_index)

Index(['Store_A', 'Store_B', 'Store_C'], dtype='object')

In [93]:
sales_feb_aligned=sales_feb.reindex(common_index)
sales_feb_aligned

         Sales
Store_A  260.0
Store_B    NaN
Store_C  310.0

In [94]:
sales_diff=sales_feb_aligned['Sales']-sales_jan['Sales']
sales_diff

Store_A    10.0
Store_B     NaN
Store_C    10.0
Name: Sales, dtype: float64

In [95]:
sales_feb_aligned=sales_feb.reindex(common_index,fill_value=0)
sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310

In [96]:
sales_diff=sales_feb_aligned['Sales']-sales_jan['Sales']
sales_diff

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

# For column

In [97]:
source_a=pd.DataFrame({
    'Product':['Laptop','Tablet','phone'],
    'Price':[1000,500,8000],
    'Stock':[30,50,100]
})
source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   phone   8000    100

In [98]:
source_b=pd.DataFrame({
    'Price':[980,520,810],
    'Product':['Laptop','Tablet','Phone']
})
source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [99]:
alligned_b=source_b.reindex(columns=source_a.columns,fill_value=0)
alligned_b

  Product  Price  Stock
0  Laptop    980      0
1  Tablet    520      0
2   Phone    810      0

In [100]:
stock_diff=source_a['Stock']-alligned_b['Stock']
stock_diff

0     30
1     50
2    100
Name: Stock, dtype: int64

# Iteration in Pandas

In pandas, iteration refers to looping over rows or columns of a DataFrame or Series. While pandas is optimized for vectorized operations, sometimes we need to loop — for example, for conditional logic, debugging, or generating complex values.

In [101]:
df=pd.DataFrame({
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'City':['Mumbai','Bengaluru','Chennai']
})

In [102]:
df

      Name  Age       City
0    Alice   25     Mumbai
1      Bob   30  Bengaluru
2  Charlie   35    Chennai

In [103]:
for index,row in df.iterrows():
    print(f"{index}: {row['Name']} is {row['Age']} Years old and Live in {row['City']}")

0: Alice is 25 Years old and Live in Mumbai
1: Bob is 30 Years old and Live in Bengaluru
2: Charlie is 35 Years old and Live in Chennai

In [104]:
for row in df.itertuples():
    print(row)
    print(row.Index)
    print(f"{row.Name} is {row.Age} Years old And Lives in {row.City}\n\n")

Pandas(Index=0, Name='Alice', Age=25, City='Mumbai')
0
Alice is 25 Years old And Lives in Mumbai


Pandas(Index=1, Name='Bob', Age=30, City='Bengaluru')
1
Bob is 30 Years old And Lives in Bengaluru


Pandas(Index=2, Name='Charlie', Age=35, City='Chennai')
2
Charlie is 35 Years old And Lives in Chennai

In [105]:
for col in df.columns:
    print(f"column  {col}")
    print(f"{df[col].values}\n\n")

column  Name
['Alice' 'Bob' 'Charlie']


column  Age
[25 30 35]


column  City
['Mumbai' 'Bengaluru' 'Chennai']

In [106]:
list(df.columns)

['Name', 'Age', 'City']

In [107]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

# Conditional Example: Add Column with Custom Logic

Based on age column, i want to create a new column that will classify people as 'young' or 'senior'

In [108]:
category=[]
for column,row in df.iterrows():
    print(row)
    print(row['Age'],"\n\n")
    if row['Age']<40:
        category.append("Young")
    else:
        category.append("Senior")

df['Category']=category

df

Name     Alice
Age         25
City    Mumbai
Name: 0, dtype: object
25


Name          Bob
Age            30
City    Bengaluru
Name: 1, dtype: object
30


Name    Charlie
Age          35
City    Chennai
Name: 2, dtype: object
35

      Name  Age       City Category
0    Alice   25     Mumbai    Young
1      Bob   30  Bengaluru    Young
2  Charlie   35    Chennai    Young

# Better Way: Vectorized / Apply

In [109]:
df['Categorized_vector_1']=df['Age'].apply(lambda age : 'Young' if age<40 else "senior")
df['Categorized_vector_1']

0    Young
1    Young
2    Young
Name: Categorized_vector_1, dtype: object

In [110]:
Categorized_vector_sample=lambda age : "Young" if age<40 else "Senior"
df['Categorized_vector_2']=df['Age'].apply(Categorized_vector_sample)

In [111]:
def category_age(age):
    return 'Young' if age<40 else 'senior'

df['Categorized_vector_3']=df['Age'].apply(category_age)

In [112]:
df

,Name,Age,City,Category,Categorized_vector_1,Categorized_vector_2,Categorized_vector_3
0,Alice,25,Mumbai,Young,Young,Young,Young
1,Bob,30,Bengaluru,Young,Young,Young,Young
2,Charlie,35,Chennai,Young,Young,Young,Young

In [113]:
for i in df[['Age','City']].iterrows():
    print(i,"\n\n")

(0, Age         25
City    Mumbai
Name: 0, dtype: object)


(1, Age            30
City    Bengaluru
Name: 1, dtype: object)


(2, Age          35
City    Chennai
Name: 2, dtype: object)

In [114]:
df.columns

Index(['Name', 'Age', 'City', 'Category', 'Categorized_vector_1',
       'Categorized_vector_2', 'Categorized_vector_3'],
      dtype='object')

In [115]:
def check_mumbai_age(row):
    print(row)
    City=row['City']
    age=row['Age']
    if City=='Mumbai':
        if age<40:
            return True
        else:
            False
    else:
        return False
    
df['if_young_mumbai']=df.apply(check_mumbai_age,axis=1)

Name                     Alice
Age                         25
City                    Mumbai
Category                 Young
Categorized_vector_1     Young
Categorized_vector_2     Young
Categorized_vector_3     Young
Name: 0, dtype: object
Name                          Bob
Age                            30
City                    Bengaluru
Category                    Young
Categorized_vector_1        Young
Categorized_vector_2        Young
Categorized_vector_3        Young
Name: 1, dtype: object
Name                    Charlie
Age                          35
City                    Chennai
Category                  Young
Categorized_vector_1      Young
Categorized_vector_2      Young
Categorized_vector_3      Young
Name: 2, dtype: object

In [116]:
df.head()

,Name,Age,City,Category,Categorized_vector_1,Categorized_vector_2,Categorized_vector_3,if_young_mumbai
0,Alice,25,Mumbai,Young,Young,Young,Young,True
1,Bob,30,Bengaluru,Young,Young,Young,Young,False
2,Charlie,35,Chennai,Young,Young,Young,Young,False

# Sorting in Pandas

Sorting helps you organize your data for better readability, analysis, and logical operations — whether by index or actual data values.

### Why Sorting Matters

You might want to:

- See top-performing products (e.g., highest sales)

- Order records by name/date

- Prepare data before merging or visualizing

### Two Main Types of Sorting
1. sort_values() → Sort by data values
2. sort_index() → Sort by index (row or column labels)

# 1. sort_values() → Sort by data values

# syntax

```bash
DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, na_position='last')
```

| Argument      | Purpose                                 |
| ------------- | --------------------------------------- |
| `by`          | Column label(s) to sort by              |
| `axis`        | 0 = rows (default), 1 = columns         |
| `ascending`   | True = low to high, False = high to low |
| `inplace`     | True = modify current object            |
| `na_position` | 'first' or 'last' for NaNs              |

In [117]:
class cal:
    def __init__(self,a):
        self.a=a
    def add(self,b):
        c=self.a+b 
        return c
    def inplace_add(self,b):
        self.a=self.a+b
        return self.a

In [118]:
c_cal=cal(10)

In [119]:
c_cal.a

10

In [120]:
c_cal.add(10)

20

In [121]:
c_cal.a=c_cal.add(10)

In [122]:
c_cal.inplace_add(10)

30

In [123]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df=pd.read_csv(titanic_dataset_github_url)

In [124]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [125]:
sorted_age=df.sort_values(by='Age')

sorted_age[['Name','Age']].head(10)

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
644           Baclini, Miss. Eugenie  0.75
469    Baclini, Miss. Helene Barbara  0.75
78     Caldwell, Master. Alden Gates  0.83
831  Richards, Master. George Sibley  0.83
305   Allison, Master. Hudson Trevor  0.92
386  Goodwin, Master. Sidney Leonard  1.00
172     Johnson, Miss. Eleanor Ileen  1.00
183        Becker, Master. Richard F  1.00

In [126]:
sorted_age[['Name','Age']].tail(10)

                                             Name  Age
832                                Saad, Mr. Amin  NaN
837                           Sirota, Mr. Maurice  NaN
839                          Marechal, Mr. Pierre  NaN
846                      Sage, Mr. Douglas Bullen  NaN
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  NaN
859                              Razi, Mr. Raihed  NaN
863             Sage, Miss. Dorothy Edith "Dolly"  NaN
868                   van Melkebeke, Mr. Philemon  NaN
878                            Laleff, Mr. Kristo  NaN
888      Johnston, Miss. Catherine Helen "Carrie"  NaN

In [127]:
sorted_age.iloc[200:300]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
501,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
395,396,0,3,"Johansson, Mr. Erik",male,22.0,0,0,350052,7.7958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S
134,135,0,2,"Sobey, Mr. Samuel James Hayden",male,25.0,0,0,C.A. 29178,13.0000,NaN,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S

In [128]:
print(df['Age'].dtype)

float64

In [129]:
df['Age']=df['Age'].fillna(0).astype('int64')

In [130]:
df[['Name','Age']].tail(10)

                                         Name  Age
881                        Markun, Mr. Johann   33
882              Dahlberg, Miss. Gerda Ulrika   22
883             Banfield, Mr. Frederick James   28
884                    Sutehall, Mr. Henry Jr   25
885      Rice, Mrs. William (Margaret Norton)   39
886                     Montvila, Rev. Juozas   27
887              Graham, Miss. Margaret Edith   19
888  Johnston, Miss. Catherine Helen "Carrie"    0
889                     Behr, Mr. Karl Howell   26
890                       Dooley, Mr. Patrick   32

In [131]:
sorted_df=df.sort_values(by='Age')
sorted_df[['Name','Age']].tail(20)

                                          Name  Age
625                      Sutton, Mr. Frederick   61
570                         Harris, Mr. George   62
829  Stone, Mrs. George Nelson (Martha Evelyn)   62
252                  Stead, Mr. William Thomas   62
555                         Wright, Mr. George   62
275          Andrews, Miss. Kornelia Theodosia   63
483                     Turkula, Mrs. (Hedwig)   63
545               Nicholson, Mr. Arthur Ernest   64
438                          Fortune, Mr. Mark   64
54              Ostby, Mr. Engelhart Cornelius   65
456                  Millet, Mr. Francis Davis   65
280                           Duane, Mr. Frank   65
33                       Wheadon, Mr. Edward H   66
116                       Connors, Mr. Patrick   70
745               Crosby, Capt. Edward Gifford   70
672                Mitchell, Mr. Henry Michael   70
493                    Artagaveytia, Mr. Ramon   71
96                   Goldschmidt, Mr. George B   71
851                        Svensson, Mr. Johan   74
630       Barkworth, Mr. Algernon Henry Wilson   80

In [132]:
df_sorted=df.sort_values(by=['Pclass','Fare'],ascending=[True,False])

In [133]:
df_sorted.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S

# 2. sort_index() – Sorting by index

This is useful when you’ve set a meaningful index and want to restore or arrange it.

```bash
DataFrame.sort_index(axis=0, ascending=True, inplace=False)
```

axis=0 → Sort rows

axis=1 → Sort columns

In [134]:
PassengerId=df.set_index('PassengerId')
df_sorted_by_index=PassengerId.sort_index()

In [135]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [136]:
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

# Sorting Columns Alphabetically

In [137]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [138]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [139]:
df[['Ticket','Name']]

               Ticket                                               Name
0           A/5 21171                            Braund, Mr. Owen Harris
1            PC 17599  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    STON/O2. 3101282                             Heikkinen, Miss. Laina
3              113803       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              373450                           Allen, Mr. William Henry
..                ...                                                ...
886            211536                              Montvila, Rev. Juozas
887            112053                       Graham, Miss. Margaret Edith
888        W./C. 6607           Johnston, Miss. Catherine Helen "Carrie"
889            111369                              Behr, Mr. Karl Howell
890            370376                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [140]:
sorted(df.columns)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'Ticket']

In [141]:
df=df[sorted(df.columns)]

In [142]:
df.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

# Working with Text Data in Pandas

In [143]:
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [144]:
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: object

In [145]:
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: object

In [146]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [147]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df=pd.read_csv(titanic_dataset_github_url)

In [148]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [149]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [150]:
df['Name'].replace("Mr",'Sir',regex=False).head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [151]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [152]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [153]:
df.loc[1,'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [154]:
start=df.loc[1,'Name'].find("(")

In [156]:
end=df.loc[1,'Name'].find(")")

In [159]:
df.loc[1,"Name"][0:start]+df.loc[1,'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [160]:
def reamove_substring(name):
    start=name.find("(")
    end=name.find(")")
    new_name=name[0:start]+name[end+1:]
    new_name=new_name.strip()
    return new_name

In [161]:
df['Name Trimmed']=df['Name'].apply(reamove_substring)

In [162]:
df['Name Trimmed'].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name Trimmed, dtype: object

In [164]:
df.loc[1,'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [165]:
df.loc[1,'Name Trimmed']

'Cumings, Mrs. John Bradley'

In [166]:
df['Name'].replace(r"\(*\)","",regex=True).head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel
4                             Allen, Mr. William Henry
Name: Name, dtype: object

| Part | Meaning                                                              |
| ---- | -------------------------------------------------------------------- |
| `r`  | Raw string literal — tells Python **not to interpret** `\` as escape |
| `\(` | Escaped `(` — matches a literal opening parenthesis                  |
| `.*` | Dot `.` matches **any character**, and `*` means **zero or more**    |
| `\)` | Escaped `)` — matches a literal closing parenthesis                  |

# Split and Access Elements

In [ ]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [ ]:
df['Name'].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [ ]:
df['Name'].str.split().str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [ ]:
df['Name'].str.split()[0][0]

'Braund,'

# Strip Spaces

In [ ]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
df['Name'].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
df['Name'].str.lstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

# Find Position of Substring

In [ ]:
df['Name'].str.find('Mr')

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [ ]:
count=df['Name'].str.contains('Miss').sum()
print("Count of 'Miss' is : ",count)

Count of 'Miss' is :  182

In [ ]:
data={
    'Name':[
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email':[
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df=pd.DataFrame(data)

In [ ]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [ ]:
df['Name'].str.pad(width=20,side='left',fillchar='-')

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: object

# Categorical Data in Pandas

### 📌 What is Categorical Data?

Categorical data is textual or labeled data that represents discrete categories.

In [ ]:
class_data={
    'Name':['A','B','C','D'],
    'Groups':['G1','G2','G3','G4']
}
class_df=pd.DataFrame(class_data)

In [ ]:
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [ ]:
class_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Groups  4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [ ]:
class_df['Grouped_chats']=pd.Categorical(
        class_df['Groups'],
        categories=['G3','G1','G2','G4'],
        ordered=True
)

In [ ]:
class_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           4 non-null      object
 1   Groups         4 non-null      object
 2   Grouped_chats  4 non-null      category
dtypes: category(1), object(2)
memory usage: 404.0+ bytes

In [ ]:
class_df['Grouped_chats'].cat.categories

Index(['G3', 'G1', 'G2', 'G4'], dtype='object')

In [ ]:
class_df['Grouped_chats']>='G4'

0    False
1    False
2    False
3     True
Name: Grouped_chats, dtype: bool

In [ ]:
class_df

  Name Groups Grouped_chats
0    A     G1            G1
1    B     G2            G2
2    C     G3            G3
3    D     G4            G4

In [ ]:
df=pd.read_csv(titanic_dataset_github_url)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
df['Embarked']=df['Embarked'].fillna('N')

In [ ]:
df['Embarked'].unique()

array(['S', 'C', 'Q', 'N'], dtype=object)

In [ ]:
df['Auto_Embarked']=df['Embarked'].astype('category')

In [ ]:
df['Auto_Embarked'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='object')

In [ ]:
df['Embarked_cust_cat']=pd.Categorical(
    df['Embarked'],
    categories=['N','S','C','Q'],
    ordered=True
)

In [ ]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='object')

In [ ]:
df['Embarked_cust_cat']>'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [ ]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, object): ['N' < 'S' < 'C' < 'Q']

In [ ]:
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [ ]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

# Date Functionality in Pandas

In [ ]:
df=pd.DataFrame({
    'event':['Concert', 'Conference', 'Wedding'],
    'date':['2025-01-01', '2025-03-15', '2025-07-20']
})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      object
 1   date    3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

In [ ]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [ ]:
df['pandas_datetime']=pd.to_datetime(df['date'])

In [ ]:
df.head()

        event        date pandas_datetime
0     Concert  2025-01-01      2025-01-01
1  Conference  2025-03-15      2025-03-15
2     Wedding  2025-07-20      2025-07-20

In [ ]:
df['pandas_datetime'].dt.year

0    2025
1    2025
2    2025
Name: pandas_datetime, dtype: int32

In [ ]:
df['pandas_datetime'].dt.month

0    1
1    3
2    7
Name: pandas_datetime, dtype: int32

In [ ]:
df['pandas_datetime'].dt.day

0     1
1    15
2    20
Name: pandas_datetime, dtype: int32

In [ ]:
df['pandas_datetime'].dt.weekday

0    2
1    5
2    6
Name: pandas_datetime, dtype: int32

In [ ]:
df['pandas_datetime'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: pandas_datetime, dtype: object

In [ ]:
df[df['pandas_datetime']>'2025-04-01']

     event        date pandas_datetime
2  Wedding  2025-07-20      2025-07-20

In [ ]:
df[df['pandas_datetime'].between('2025-01-01','2025-06-01')]

        event        date pandas_datetime
0     Concert  2025-01-01      2025-01-01
1  Conference  2025-03-15      2025-03-15

# Creating Datetime Ranges

Other frequencies:

'M' → month end

'MS' → month start

'W' → weekly

'H', 'T', 'S' → hour, minute, second

In [ ]:
pd.date_range(start='2026-02-01',end='2026-02-10',freq='D')

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start='2026-01-01',end='2026-03-10',freq='ME')

DatetimeIndex(['2026-01-31', '2026-02-28'], dtype='datetime64[ns]', freq='ME')

In [ ]:
pd.date_range(start='2026-01-01',end='2026-03-10',freq='MS')

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01'], dtype='datetime64[ns]', freq='MS')

# Date Arithmetic

In [ ]:
df['next_week']=df['pandas_datetime']+pd.Timedelta(days=7)

In [ ]:
df['next_week'].head()

0   2025-01-08
1   2025-03-22
2   2025-07-27
Name: next_week, dtype: datetime64[ns]

In [ ]:
pd.Timedelta(days=7)

Timedelta('7 days 00:00:00')

In [ ]:
pd.Timestamp.today()

Timestamp('2026-03-09 04:02:49.248994')

In [ ]:
df.head()

        event        date pandas_datetime  next_week
0     Concert  2025-01-01      2025-01-01 2025-01-08
1  Conference  2025-03-15      2025-03-15 2025-03-22
2     Wedding  2025-07-20      2025-07-20 2025-07-27

In [ ]:
df['days_to_event']=df['pandas_datetime']-pd.Timestamp.today()

In [ ]:
df.head()

,event,date,pandas_datetime,next_week,days_to_event
0,Concert,2025-01-01,2025-01-01,2025-01-08,-433 days +19:55:20.435977
1,Conference,2025-03-15,2025-03-15,2025-03-22,-360 days +19:55:20.435977
2,Wedding,2025-07-20,2025-07-20,2025-07-27,-233 days +19:55:20.435977

# PANDAS COMPLETED

=================================================================